---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app terraria
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: terraria
      version: 0.1.8
      sourceRef:
        kind: HelmRepository
        name: terraria
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nameOverride: *app
    server:
      service:
        type: ClusterIP
        port: 7777
      password: chicago
    image:
      repository: ryshe/terraria
      tag: tshock-1.4.3.6-4.5.17-3
