---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflared
      version: 2022.7.1
      sourceRef:
        kind: HelmRepository
        name: kylesferrazza
        namespace: flux-system
  values:
    replicaCount: 2
    tunnelID: "${CLOUDFLARE_TUNNEL_ID}"
    auth:
      accountTag: "${CLOUDFLARE_ACCOUNT_TAG}"
      tunnelName: "${CLOUDFLARE_TUNNEL_NAME}"
      tunnelSecret: "${CLOUDFLARE_TUNNEL_SECRET}"
    ingress:
    - hostname: echo-server.zweifel.cloud
      service: http://echo-server:8080
    # This rule sends traffic to the built-in hello-world HTTP server. This can help debug connectivity
    # issues. If hello.example.com resolves and tunnel.example.com does not, then the problem is
    # in the connection from cloudflared to your local service, not from the internet to cloudflared.
    - hostname: hello.zweifel.cloud
      service: hello_world
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404