# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_TAG: ENC[AES256_GCM,data:g14NXz8W7m5Zh6HCuizyVA4qXq6OH1LeMNy6Jz/Xoew=,iv:wfxYJTULWawFVNmMFXZOQkrEwaKaYZcky8ALW8BhjH4=,tag:k5ENhYpS/hrOiNo/Hdiu3w==,type:str]
    CLOUDFLARE_TUNNEL_NAME: ENC[AES256_GCM,data:uNZpMjaI73ax97xN,iv:YTBrcCBwZstbaCc50f0rOF5woky0BkXY+736b+zxsZo=,tag:FyA0ozWX9LzLqY6gfsCalw==,type:str]
    CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:DYMDgkl15atjHFuzprDsLMt1JnSdMNcV5sL7dHu+cj0xV+0kOz0gcr++Qz4=,iv:pM6+res2FpjyIPdBWqPJFPqwhRV5itPk6Siu+SpljSU=,tag:8QzAqDsddZ5hUlu4Yoh0IQ==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6L+aDK+qYEX8AqRB3pfJ+9vcJ7R2OEFggCAHWWPRVF4qnKEO,iv:06CW6oEUgxWB/AbhQUC8v46ouMKaYlqb4maNBU8riVI=,tag:2BixXRPEiXvhBLSsjnAdmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaGVKRS96cnhDZC9aV3Zs
            aUJqb0dUT1h4TXY1WFZCTHVTWEFqMTM3VWtrCnpTQnRCVWRKcHFXRTI4ckVzK0w1
            NjZDMDU1eThzRVBXTDIvOFJXRFNxbDQKLS0tIHdwM2JXNGlQUnpjd2hYWkZ0SENT
            bzdNdUc1b1NBNkVWc0JHd1hUNXBITHMKc4htvRcMiUq0uSDuhzYwQuzkP6vfy0cF
            8PO4vTWSSimTGYRj5SUaz1dUPR+zdt5e/wNhfQg4FaQgBZT/nn8wfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T18:41:17Z"
    mac: ENC[AES256_GCM,data:X+lHXEpJ8WwW9UuRs31TBx0REGv29y+0zpeUqXukzZhB+aiHc7g7vGPno9YXXy2CcDggDEGdXheVA0kFELyxSUSLbYgTBSLfwgIr2UyOQs0aE+WM/8U3L8zUiy4zxLUt3GU0Wqe+3atJQ/oxTdLAzCqFzFpDV2xEgKcfTAqv2Bc=,iv:Cp1g3TtQXPa3nr4Z8siE0u0sUuAUSsO9RgUWE3ywWjs=,tag:Bg35Tj1s0NLLhl0nR+JU/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
