# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_TAG: ENC[AES256_GCM,data:lQUaUemkrMgDSV5g3XXiS13EGRXWQ5CXip7VNX9PnhA=,iv:Ll0IoMR7rJXpY+BTxCOz1VClxnOzMo8va7/Lbfphf/w=,tag:MhK7uDVUKb3Nh0IWrkzmPA==,type:str]
    CLOUDFLARE_TUNNEL_NAME: ENC[AES256_GCM,data:IZv9m1Q9ILP0sV2T,iv:jCPa48FQjwpTDslcSW+hyr3X55wdVQJZMXDO+NTAKuY=,tag:ttoF+rWh8KSh9W97n8FS4A==,type:str]
    CLOUDFLARE_TUNNEL_SECRET: ENC[AES256_GCM,data:WKX8uQ//rLRl9ayrQ6IMjIWKEj2Gb08Rps0Gl8b2SjTEtW7coxIxd+7MDug=,iv:cberYMBLVXWBYc+8iZOXJ111f/dXRzDrUIqXnEIFVWY=,tag:19+p4q5UCIVOoHLBlRViwg==,type:str]
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:tkoJbehNMigSLC8BNV3K21LQorZi8wdmaagjcdr75ho1lH/z,iv:KYvC3Mj6Q9b+xqq87Uc+Ps4oAQWTHmCIlmIdx+cfo5c=,tag:phi5piLRVGoMoOOaZYuruQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVkZGbFJzc0NBbS9NYkFF
            dG5POFo1bzZrcGM4Qk96d0kvQmxueGY2ZFR3ClhoN2tOQ1RYOFVyc2VjZm52aDFW
            MHNGQjNteDdxQlBjbCtMZTd3VFJ2aGsKLS0tIEpkZVgwMmd6K1gra003U3d0OStv
            U3dYd3VpVzBXVi9QamJneUZ4aDJaeXcK4ZGfIAQtjtu5tbbOJBx7UYuGszEH3bKZ
            UzhUAN+4oudBvGKkU4hH9M9iZLdYGwQypxb6GY8QlTEeLoiXbd7VYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T18:20:45Z"
    mac: ENC[AES256_GCM,data:YYNXE00tKE2bubnECWZcmYXST5HQSq6ssa648fc6WeYE1cKg9IVOCdGWRk/fsoQEq84vS7Xi1VvaI1d+lbv9gGKPoLrFA7zKgSyP2fn52ee32IgW5vEDlHnJWzCCTLTspfnmp6hXClfMDcVJRXlarucm8ErZK1wyyiBPJlvqbxA=,iv:5WWYfT6c6LDzmXumqcHhcQC1mQMvkSeznaMASCu0Qtg=,tag:cnFoTmlWc1bpOu/CkPMVbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
