# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared
    namespace: networking
type: Opaque
stringData:
    tunnel-config.json: ENC[AES256_GCM,data:UsffR5BFXw26lw+Bc9qt6dcWCja1mn+tWKJByRtXOnxzDaMfSYpFxdHoiRr1SQ4A0ASD1TkgIX2n1Xy7owCetJvBNMP2eeNuifv/iSIMCNwNSNUh7ac3S9E+C5045b6RvxcGaV8dOjYGOoiImV7lAxYj+pvXRbxJ7wdmhGxCXb0J1Q9Yjd26MCDY9TlevjpKQlUS5ON5bg2XSTGb8mkAggtp3qwK64jPdAdJWmGuNZR+trmpWyY8YdjKwYEJy9SfgE5SOQKd2FyOBdozCiA8,iv:dQdLf86C1nWkFAVl8KFBjZAnugkaPE/i8l0GIF0OZu4=,tag:iFPN0tUM/PMw5D3SQjIfoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MVdCR1VwVUUrTmVxcVhB
            S25JcEt1Vk56NDRkZVBEdzRxNmlhVTlIUENVCnUxa28vTTl2MUxhMThyV0lRY2Rv
            T1AveUQ3Y0ZSc01Ock10eU5OaFpjWjAKLS0tIGRYV3RGZVArRllleGpQQmkySDF4
            ZWNjMDZ4bWtuRTNNZkNoQ1dyQzRCVTAKGR2bbEqpcDVkm9f+4JVQtMxOldX/A30t
            gTm30VYQ1g9nWaEeAdTAVol15Zw87LKONhTde9SlEZD7a82sSWnR2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T19:24:08Z"
    mac: ENC[AES256_GCM,data:6J6tUu45XrDdjwl4VOrNfr/VQ3JGrb6ymdJVijU9qJseNBlhDaub2yVaB9pe4fyI8EsbmqhwHCWENQUg5u0QxezyoVZA0Le5TVbpgmRyrVpHcIL6PehMmrHUk949/iX+UfF4CYXqJeoYNXvVt1+uNeyUMYaqNEIXEQUG3e/xFz0=,iv:NKhgEA6NYedkYxe8xGDBTAYZT3npe4sT4bQ0JUzHOsc=,tag:supo8SqPDO37xfH8bMpa5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
