# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:xinQfp5jUAAWOEWgNN1kWXMeUicgF8CClmg0aIuUAUZdskZA1Q==,iv:+dNnGEaf4N8xCOuuhX5H6pmmnIqUTAclNUF5tu74lJU=,tag:NYsw3smsHo0uSsPCzNlUqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SlRrbU1oeXpmMmoyUldw
            OTgrQWhGZERnSXVTbk9KeWFCbENMcit1b21nCmFjTjVkSXBRa3dlWTNOZC9QbnUr
            QWVXK3A3dGlkOFZ3ZzBrVThDalpOSGMKLS0tIDNGYUR1aGh3YnNyU2syY205dzcy
            NC9lOUR6TzUwb1hUS3doVmF1N2VvY1UKZya3NEjmz1l0I82F10nW/bQPL0TOrPcu
            ARjGc1Pg121VGPeTgCIYNA4MQ8dWCRy/UHWu6Swv1j6pTL4yDI4KFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T19:11:00Z"
    mac: ENC[AES256_GCM,data:6zUj2hYcXLRNJIdBq0lsVMgFrvBmB38VHl4b2KTcdKqQsAmbG6/Fa0OpIUF7rjFI2lWtVGb3G3yyL2dijdOrnwDCLPx0MrCWfU+wRZfR+IiEZnfYflhA3+i8mc/pm+gTUetJXb7lSvdR0tO1nJ8MIekrsglolRVeV1J8gXECXxI=,iv:e9YuDloUUCNzGZnQ9NhV5BGE1gTNeTTrMZtVooEqfRA=,tag:7l6i5rLkeItWrjQcROt9tw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
