# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sLcj16BTU0bbA9ehxCkzQkTY,iv:uOBUySX/Jl8217NUKs36Cm+m4A0Y02ri/f5R8zilXgI=,tag:VkyzdadqvRXduS/cZ0cRZg==,type:str]
    api-key: ENC[AES256_GCM,data:bK5rdOlotdv/TE2L/bBJnjP1lWd9Li/nc5cOfWSOXlg8B3/68A==,iv:TVo+ZTN6d3mOZNl9VPwf3egffnKCy9/K5agDcHA/ev8=,tag:4wbEWcLxP39QGCiimqzLJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK1kzT3lRK3FFUTFBbVUz
            djNMSncvSExkWDJaS1hyV0hEbW5EdUQxQ2hNCkRPeDF0QytQYUhaY1A0Qng3eGFq
            R3l0TndFK20xMmJSSy9iTCtuR2dUejgKLS0tIHVuWmUyNWNEUkJZbW1iNUdBTFhr
            M1R2aklPV3JGMzhsTUtZNkhvYzVuRW8KAvijNuv526qqdmE7p0GTSLxneI/WFf3k
            UDG5iLhrbefvqqS8wEb478GzhA7o5WlcK7J4D+FEE4IRgcX5fmflqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T12:58:18Z"
    mac: ENC[AES256_GCM,data:sIeVhyj/3LnvStvOn005FZDNn8+VoxSG2bldWQxw1x0i3vD+8yc4A2iIyOqdZl/XoZWRS6c+w18c0woA11KBwoDtY66/onHAtJYXO47TFWsxF9BPyR61wMScj+8Xtw47yqikhyW3pcqA7NgS806Kz+0PplHKALVhk5BMfv1jzjw=,iv:ZAuSZXjbb4NQfJ8jFlgxnJnOBjBPZwN8dr/S2e4xTzc=,tag:ktTYw80qaOO4pwn4ileVFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
