# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:07Q6VX+kMLnyv6IBn/BXOHxb,iv:877omAcB4JykgdnWH2ZXqOvS/1pbh4Ni02dMqk6d/Bs=,tag:2aQFzKWJfkXE+zqof5o0WA==,type:str]
    api-key: ENC[AES256_GCM,data:u4au1FAb09BMP45DaCqPOjRqrwQLQ9rN+df8s5oM9D9ernllbA==,iv:gU0FKVmJFccHu5TprJLBFD/1mrJPfmPrZxB7CzhkSeA=,tag:dh4iELoVA0BUfsIJOqI3rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidGNqR0wxTk1md0dQVWM4
            L2ZsQkxvdGVubDlDYmVmNDNpdlNDU284RHp3CmwyT2Q5aXo2RG1PL2xiSjJvbkls
            MTBZc21XR1RkSFoxUnZFdEYyUHo4WEEKLS0tIFBXSUtYNDhYLytDUUYwbEh2VXJ4
            R1pCaHNKN0MvbWxEMkdGdmcwbE05V0kK0Vn3ksqKEdWze2pDodS128XQb7FuLM9U
            NtOs8zc33uIWd7ztn2YW6Q7X4F6qT0Zb/wFVKuK+KeHGvWXv+39bUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T18:20:45Z"
    mac: ENC[AES256_GCM,data:haHWBaLej0W1u7RsZ9TkyivUDnpZ+Wk32T2zhnSvQYi/5zKLE/8HhG1lOmJTrXoVJu8om6S5zEKPdAiV7RVCQJVkbCdt2zq7h+ApSmhbzU8eiSfkNuYMLKKxilGtPMi8QH6KGvyR+jVHfnkOAaF85gXTPfyGdz75E9n8ORZVuio=,iv:nphkUrxgt6eSwZmFmeSlTU2Emb2WvdEZvtaZ+zPsI1A=,tag:hNc1A1WAoBFU7vCNDfK/QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
