---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Chicago
  METALLB_LB_RANGE: 10.0.0.243-10.0.0.253
  METALLB_K8S_GATEWAY_ADDR: 10.0.0.244
  METALLB_INGRESS_ADDR: 10.0.0.245
