# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9bMTBUY2dpPsT0IesA==,iv:95v+2nipdVvop69O08xUrQo8Vl4p0948/Xxyrbf0iuY=,tag:RaDUHfAudR7ptqQYlxpShA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SNrPkxBJVnZet/UEE5P3VUXY,iv:Cvo00s4mvu4D+KUi4AlH/zc+w+hD5jvmOl/a03UK/+o=,tag:T1kSADC5MVQCRu0LKLJ22A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMHRaUlFTcG9DZ2VwUkJ6
            Y3lZV0FUeFF2b3pHTzA0bUx6bnZLS0pySmg0CmZkTEU5bzBhd2V6UTIvbWNTZkEr
            Q1VFQXdaVjN0SHJTNEY4Ui9Ia0ROb2sKLS0tIHZpVkZJd0JVb3AveHd1VlJNSXFj
            QzY2NFJSNzRyZ2x2RjFoY3JUZThhdGMKPcMU5eFRWAbpL/r/HXfsrb1s3p//Ex2l
            1YPl0F+BPtm9gZI8GrjnHaJdgA1xSmU5vAhjw12mYp0l04wBRp8oFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T19:24:07Z"
    mac: ENC[AES256_GCM,data:E+PaoKYtpz2bH2iTEgNiVrTG5BqmOYV6AardhThEvPG6DZB8D6YrkGHMxo0FdzPx50lYD0UqgAqNZ/ZvRlKEVkNv3euwiIP4MC45KOzE6JgHF05qEnSb+h9yfFfwxt55X9AM79brlFsldPrkefDcOgVoJFCqaw/rym5Lf93KO9U=,iv:yy0N6aDkeHVF5siSj8gRyv2jERiM5hfDn5ZWUUWuz2E=,tag:e5UKP02xz2GMwLtVh6BL6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
