# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:TQ7bmlNwusig+Q5v7Q==,iv:HgNBcI/itbI4hq8h4xcMtsT/q2R/qE3K0iPinrrN7ko=,tag:ayOkYnkuuAtaQFDaZGC/0w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Xuq6yx9fLh7c5f47iq1Zs8O0,iv:nYdOrE3OIEwPrKoN8JjzSXOhVWvrJqPiPI3K+P4pJ+Q=,tag:ivkt5cgT+4twGYfyTbh7vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQN2tFanBVQWZST0Fqam5I
            L3kzcUs5SU9ld2l4RWM3UEtGZTlJOTB2bXpnCm5OZDJPb1pNRThWcGFoYzREdVBZ
            M0tvbis1QmpzMnZQdW5lUTRBNnlMZUUKLS0tIDlkbklqRkNNckNGc2M2eWZGZ1VF
            TzN5S1Z3aWxDUDZ2WTZoczhpdUNhbjgKk9dFBpzQZHnmWgV2MkTJE+DaM6Mzx9gc
            UKw1XursBiO47nSSITK8pjtZHBPlRI0tIrXkNHl6E2rj0KN3uF1Oag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T12:58:18Z"
    mac: ENC[AES256_GCM,data:9JygmR5mmqiVn/louoprxIF61mNoZsONPLitvGbySSigYfLDKlE4Oydr209i/L84L1CIJcWSDsMU4viDtxa+12F6/xrcgzuk6GL0QcbpWg+4kOQU86LQMP4XAElmUc0FHwWdmmbLz69twOE4WgVTM/BN8uDtBTeZuCaXrkR+tuA=,iv:E+DAm5ltOkoDp/PKHTffL7t6S9qyk6EfVQnTu9jEczM=,tag:H5fLXy0QLwcGS+FuWPIc2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
