kind: Secret
ansible_user: ENC[AES256_GCM,data:ZHk92EyoEXI=,iv:QQ4z4j/XNPb+zb1b1eeJSWgeXnu2QGzvHcfmFEr3Y4Q=,tag:ur3QOqAOmeGZTJv5S2+nfg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:2kAL5Q+nRvYnvc0ZStw=,iv:N2UVvqH7XZ88Ib5GDTtCd+MgprCK0Y8jBi1LBbEIWIU=,tag:LSz35BksccYre/Rnm3Cbmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUW0rZllJN2VjTEltVi8w
            V21POEoyaUV2aFMyM3RYODdyeW1SeG9iY1JNCmwyK210dHlYTmtjYko0UVBWcDZ5
            cEpEZ3V1QUZRZ2lBb1lUMFFjQVNtYjgKLS0tIHdXUTM1UmlHK0NKNmNkSDZ5Njh4
            SEltNVJpS0NXM3dpRFU2WGdBRUhhTUEKIChcTnacjkOE7OzAE2oFI45TAEX9Qt8t
            bFIFmm4KsFgwkLnhJv+xh6HJfvAphLkpPKWlCQxlLMtPaefjUJRsPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T19:11:00Z"
    mac: ENC[AES256_GCM,data:M2AnZkF+0Ql5zwUbL/KoD8YFKhXjoBc5RWtxz5heWoaTI9UWDCdYBc09UgeG5voOQP2udfWE26HEtsiMoqHahfEDlbqzk78t/gyicJczfAdbtz5r5DSyJCyA838tRHQF2kkGTKVvHOMev+efhiT7gX70RtGyuAk1zrb3t4ldC+s=,iv:ZNgsvOQV6zotjtorPAgRjn6E5niFcMwzZ8czCzM6yoA=,tag:FsykA0UpJFHk5y9FB1mWZg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
