kind: Secret
ansible_user: ENC[AES256_GCM,data:NYUcpqyEFcs=,iv:7HiKh9m58prNtJV95d6yhbczWjfwgfgCGTJWp/HHI3w=,tag:NZNfAF8d8AqaieXB1TsECg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:68cd4nbIE3MF7jETuy8=,iv:1g8jrp1F0WsogySobe7bJ+B1qUmSsfYce7pCyzP4AzI=,tag:fXJAnl60OiZm3zq01iX0cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16ekfp5prq8qvcm8wye3hq83lyaa7aw8melqhhrsk6ep37tx70ymsfeuprj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtandza2E4UFZqZUJOVUlJ
            VGtrWTRhMEp3VVI4dGMvRnI5NWpIZURiUUMwCldxcm4rWmVDSVRtUGNjc2dMMkxm
            R0RyQ0JtU1FrS2lwWm4vQjNNVHZUbVkKLS0tIFhwUkxHMzZMQmo2cG5SUFdpN0Qx
            ZUJENDFlRzY3SGwyYjk2cnhoWnd5ZncKJvQcUIVS5/N5LcomKOTIT1W1p3r8FjSB
            D6WXT6E7yguc/0mGvvDQUKME6hmOSqygMgJu7XTG7BB3ftTaM+nxlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-11T19:11:00Z"
    mac: ENC[AES256_GCM,data:OTBVjwuSH7wLg+BVP5uzh74t2h9jB57KhwjEkQ1YQVolatTUlzLzh5SgbQ6zxn0CHA3+q1XmtXW25lVenxSRK7C45bEGxlihSWwVllHOAFfLijbEs22BeL3GTlloBkAz/uoYkyMY5oz74RJ/it37UlORiQVKbxaDi7ujEm7WnwU=,iv:PmQ5tlhaEprDAFvYnbYttmPSg0FCnUn6rSY+UNZ5PzU=,tag:O01KBMQgs6n+iLUbbS69rA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
