# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-ddns
  namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_ACCOUNT_TAG: ${BOOTSTRAP_CLOUDFLARE_ACCOUNT_TAG}
    CLOUDFLARE_TUNNEL_NAME: ${BOOTSTRAP_CLOUDFLARE_TUNNEL_NAME}
    CLOUDFLARE_TUNNEL_SECRET: ${BOOTSTRAP_CLOUDFLARE_TUNNEL_SECRET}
    CLOUDFLARE_TUNNEL_ID: ${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}
