# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared
  namespace: networking
type: Opaque
stringData:
    accountTag: ${BOOTSTRAP_CLOUDFLARE_ACCOUNT_TAG}
    tunnelName: ${BOOTSTRAP_CLOUDFLARE_TUNNEL_NAME}
    tunnelSecret: ${BOOTSTRAP_CLOUDFLARE_TUNNEL_SECRET}
