# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared
  namespace: networking
type: Opaque
stringData:
      tunnel-config.json: >
        {
          "AccountTag": "${BOOTSTRAP_CLOUDFLARE_ACCOUNT_TAG}",
          "TunnelSecret": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_SECRET}",
          "TunnelID": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}",
          "TunnelName": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_NAME}"
        }
